line-length = 100

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]
"settings.py" = ["E501"]
"task_manager/migrations/*.py" = ["ALL"]
"locale" = ["ALL"]
[lint]
preview = true
select = ["E", "F", "I", "C90"]