line-length = 80

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]
"settings.py" = ["E501"]
"task_manager/migrations/*.py" = ["E501"]
"task_manager/users/migrations/*.py" = ["E501"]
"task_manager/labels/migrations/*.py" = ["E501"]
"task_manager/statuses/migrations/*.py" = ["E501"]
"task_manager/tasks/migrations/*.py" = ["E501"]
#"task_manager/labels/forms.py" = ["E113"]
#"task_manager/statuses/forms.py" = ["E113"]
"locale" = ["ALL"]
[lint]
preview = true
select = ["E", "F", "I", "C90"]